name: On Tag

on:
  push:
    tags:
      - 'v*' 

jobs:
  
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Toolchain for ${{ github.ref }}
        draft: false
        prerelease: false
